export epsmat_bgw, eigenvalues_bgw, vcoul_bgw
"""
Read `epsmat.h5` and `eps0mat.h5` from `BerkeleyGW`.

	read(epsfolder, ::Type{epsmat_bgw}; ωindex = 1, have_negq0::Bool = true, negq0file = joinpath(epsfolder, "eps0mat_neg.h5")) -> DielectricMatrix_scalar

Read two files: `epsfolder/epsmat.h5`, `epsfolder/eps0mat.h5`, and they should contain all irreducible kpoints.
`ωindex` (accepting an Int or Vector{Int}) specifies the frequency index(es) of the dielectric matrix data to be extracted.
If `have_negq0` is true and `negq0file` exists, it will be read as the dielectric matrix at -q0, and the data can be used to handle some divergent problems and improve the accuracy of the results.
Note: need use `write_vcoul` in `epsilon.inp`.
"""
struct epsmat_bgw <: FileFormat end

"""
Read `vcoul` from `BerkeleyGW` if use `write_vcoul`.
"""
struct vcoul_bgw
	qpoints::Vector{ReducedCoordinates{Float64}}
	Glists::Vector{Vector{ReducedCoordinates{Int}}}
	vals::Vector{Vector{Float64}}
end

"""
The format of `eigenvalues.dat` generated by `absorption.x` of `BerkeleyGW`.

	read(path/io, ::Type{eigenvalues_bgw}) -> eigenvalues_bgw
"""
struct eigenvalues_bgw <: FileFormat
	neig::Int
	vol::Float64
	nspin::Int
	nspinor::Int
	eig::Vector{Float64}
	dipole_abs2::Vector{Float64}
	dipole::Vector{ComplexF64}
end
