export FileFormat
export BAND_dat, POSCAR, RESPACKU, RESPACKJ, QEcell, QE_wfc, QE_xml_new, dat_eigenvalue

"""
	abstract type FileFormat end

The file format we supposed is its subtype.


	read(path::AbstractString, ::Type{T}; kwargs...) where{T <: FileFormat}
	read(io::IO, ::Type{T}; kwargs...) where{T <: FileFormat}

Read data from a file or an IO stream in the specified file format.


	write(path::AbstractString, data, ::Type{T}; mode = "w", comment = "", kwargs...) where {T <: FileFormat}
	write(io::IO, data, ::Type{T}; comment = "", kwargs...) where {T <: FileFormat}
	
Write data to a file or an IO stream in the specified file format.

- `mode`: the write mode used by [`Base.open`](https://docs.julialang.org/en/v1/base/io-network/#Base.open)
- `comment`: it's the comment line in file, and mostly is the first line.
"""
abstract type FileFormat end

"""
Its format is the same as "BAND.dat" generated by vaspkit, contains band structure.

	read(path/io, ::Type{BAND_dat}; readkname='N', smoothband='N') -> (band, kline)

- `band`: is a matrix with size (nband, nk);
- `kline` is a instance of [`Kline`](@ref).
- `readkname` determines whether the file contain the block of `Kline`.

	write(path/io, band, ::Type{BAND_dat}; kline)

- `band`: can be Eigen, Vector{Eigen} or AbstractVecOrMat{<:Real};
- `kline`: a instance of [`Kline`](@ref) with a empty default.

!!! note
	(nband, nk) = size(band)
"""
struct BAND_dat <: FileFormat end
"""
`POSCAR` is the input file of vasp, contains the structure of unitcell.

	read(path/io, ::Type{POSCAR}; period = Bool[1, 1, 1]) -> Cell

- `period`: represents the periodicity in three directions, should be a vector with 3 elements, and each elements should be `1` or `0`.

	write(path/io, cell::Cell, ::Type{POSCAR}; format = "Cartesian")

- `format`: can be "Cartesian" or "Direct".
"""
struct POSCAR <: FileFormat end
"""
The format of output file `dir-intW/dat.Wmat` of RESPACK, also `dir-intW/dat.Vmat`.

	read(path/io, ::Type{RESPACKU}; norb::Integer) -> wannier90_hr

- `norb::Integer`, the number of orbitals.

Compared to [`RESPACKJ`](@ref), this method will read all the data in the file including onsite term.
"""
struct RESPACKU <: FileFormat end
"""
The format of output file `dir-intJ/dat.Jmat` of RESPACK, also `dir-intW/dat.Xmat`.

	read(path::AbstractString/io::IO, ::Type{RESPACKJ}; norb::Integer) -> wannier90_hr

- `norb`::Integer, the number of orbitals.

Compared to [`RESPACKU`](@ref), this method will read all the data in the file except onsite term.
"""
struct RESPACKJ <: FileFormat end
"""
The format of cell structure block in `pw.in`.

	write(path/io, cell::Cell, ::Type{QEcell})

"""
struct QEcell <: FileFormat end
"""
The format of wave function in `pwscf.save/wfc.dat`.

	read(path/io, ::Type{QE_wfc}) -> QE_wfc

"""
struct QE_wfc <: FileFormat
	ik::Int #index of kpoint.
	xk::ReducedCoordinates{Float64}
	ispin::Int #1: wospin or noncolin.
	gamma_only::Bool #only gamma.
	scalef::Float64
	ngw::Int #don't know!
	igwx::Int #the number of G or components
	npol::Int #1: wospin, 2: noncolin.
	nbnd::Int
	rlattice::ReciprocalLattice{Float64}
	Glist::Vector{ReducedCoordinates{Int}}
	components::Matrix{ComplexF64} #[igwx, nbnd]
end
"""
The format of `pwscf.save/data-file-schema.xml`.

	read(path/io, ::Type{QE_xml_new}) -> QE_xml_new

"""
struct QE_xml_new <: FileFormat
	cell::Cell{ReducedCoordinates{Float64}}
	fft_grid::NTuple{3, Int}
	nk::Int
	# kpoints::Vector{ReducedCoordinates{Float64}}
	nspin::Int
end
"""
File `dir-wfn/dat.eigenvalue` contains electronic band structure, output by wan2respack or RESPACK.

	read(path/io, ::Type{dat_eigenvalue}) -> Matrix{Float64}
	write(path/io, band::Matrix{<:Real}, ::Type{dat_eigenvalue})

"""
struct dat_eigenvalue <: FileFormat end

"""
epsmat.h5 from BerkeleyGW

	read(path/io, ::Type{epsmat_h5}) -> epsmat_h5

"""
struct epsmat_h5

end

include("./wannier90/wannier90.jl")