export FileFormat, FileFormatIO
export BAND_dat, PBAND_dat, POSCAR, RESPACKU, RESPACKJ, dat_eigenvalue, epsmat_bgw, eigenvalues_bgw, epsmat_yambo, WanIntijkl0, WanIntijklR

"""
	abstract type FileFormat end

The file format we supposed is its subtype.


	read(path::AbstractString, ::Type{T}; kwargs...) where{T <: FileFormat}
	read(io::IO, ::Type{T}; kwargs...) where{T <: FileFormat}

Read data from a file or an IO stream in the specified file format.


	write(path::AbstractString, data, ::Type{T}; mode = "w", comment = "", kwargs...) where {T <: FileFormat}
	write(io::IO, data, ::Type{T}; comment = "", kwargs...) where {T <: FileFormat}
	
Write data to a file or an IO stream in the specified file format.

- `mode`: the write mode used by [`Base.open`](https://docs.julialang.org/en/v1/base/io-network/#Base.open)
- `comment`: it's the comment line in file, which is the first line mostly.
"""
abstract type FileFormat end

"""
Its format is the same as "BAND.dat" generated by vaspkit, contains band structure.

	read(path/io, ::Type{BAND_dat}; readkname=false, smoothband=false) -> (band, kline)

- `band`: is a matrix with size (nband, nk);
- `kline` is a instance of [`Kline`](@ref).
- `readkname` determines whether the file contain the block of `Kline`.

	write(path/io, band, ::Type{BAND_dat}; kline)

- `band`: can be Eigen, Vector{Eigen} or AbstractVecOrMat{<:Real};
- `kline`: a instance of [`Kline`](@ref) with a empty default.

!!! note
	(nband, nk) = size(band)
"""
struct BAND_dat <: FileFormat end
"""
Its format is the same as "PBAND.dat" generated by vaspkit, contains band structure and the projection value.

	write(path/io, pband, ::Type{PBAND_dat}; kline, projection)

- `pband`: should be a AbstractArray{<:Real};
- `kline`: a instance of [`Kline`](@ref) with a empty default.
- `projection`: Vector{String}

!!! note
	(nband, np+1, nk) = size(pband)
"""
struct PBAND_dat <: FileFormat end
# struct PBAND_dat <: FileFormat 
# 	kline::AbstractBrillouinZone
# 	band
# 	projector
# 	projection
# end
"""
`POSCAR` is the input file of vasp, contains the structure of unitcell.

	read(path/io, ::Type{POSCAR}; period = Bool[1, 1, 1]) -> Cell

- `period`: represents the periodicity in three directions, should be a vector with 3 elements, and each elements should be `1` or `0`.

	write(path/io, cell::Cell, ::Type{POSCAR}; format = "Cartesian")

- `format`: can be "Cartesian" or "Direct".
"""
struct POSCAR <: FileFormat end



"""
Read dielectric matrix from `Yambo`.

	read(epsfolder, ::Type{epsmat_yambo}; ωindex = 1) -> DielectricMatrix_scalar

Read data from `epsfolder`, and also need the `SAVE` folder which is assumed in the same directory of `epsfolder` by default.
`ωindex` (accepting an Int or Vector{Int}) specifies the frequency index(es) of the dielectric matrix data to be extracted.
Other kwargs:
- `savefolder::AbstractString`: default is `joinpath(parentdir(epsfolder), "SAVE")`, only need `ns.db1` at present.
- `format::Symbol`: default is `:netcdf4`, which is used by [`NCDataset`](https://juliageo.org/NCDatasets.jl/stable/dataset/#NCDatasets.NCDataset).
- `suffix::AbstractString`: it will be set one of `["em1s", "pp", "Xmpa", "em1d"]` automatically if not specified, 
which is the suffix of the file containing the dielectric matrix data in `epsfolder`, 
including `ndb.\$(suffix)` and `ndb.\$(suffix)_fragment_\$(iq)`.
- `qgrid_atol::Real`: default is `1e-6`, which is the tolerance to translate the qgrid from float to fractions.
- `qgrid`: if not specified, the qgrid will be deduced from the irreducible qpoints; if specified, it should be a vector of Int.
"""
struct epsmat_yambo <: FileFormat end

"""
The file contains U_{i0,j0,k0,l0}(without U-type).

	read(path/io, ::Type{WanIntijkl0}) -> Array{VT, 4}
	write(path/io, intvalue::AbstractArray{VT, 4}, ::Type{WanIntijkl0})

where `VT <: Union{Float64, ComplexF64}`.
"""
struct WanIntijkl0 <: FileFormat end

"""
The file contains U_{i0,jR+R_j,kR,lR_l}(without U-type).

	read(path/io, ::Type{WanIntijklR}) -> WanIntijklR{VT}
	write(path/io, intvalue::WanIntijklR{VT}, ::Type{WanIntijklR})

where `VT <: Union{Float64, ComplexF64}`.
"""
abstract type WanIntijklR{T <: Number} <: FileFormat end

include("./wannier90/wannier90.jl")
include("./BerkeleyGW.jl")
include("./QE.jl")
include("./RESPACK.jl")

FileFormatIO = Union{BAND_dat, PBAND_dat, POSCAR, RESPACKU, RESPACKJ, QEpw, QEwfc_dat, dat_eigenvalue, eigenvalues_bgw, vcoul_bgw, WanIntijkl0, WanIntijklR,
	wannier90_nnkp, wannier90_chk, wannier90_eig, wannier90_xsf, wannier90_UNK, wannier90_amn, wannier90_mmn, wannier90_win, wannier90_hr, wannier90_centres}
