export QEpw, QEwfc, QEwfc_hdf5, QE_xml_new, QE_wannier
"""
The format of `pw.in` for Quantum Espresso.

	write(path/io, title::AbstractString, ::Type{QEpw}; kwargs...)

kwargs:
- `cell::Cell`: default is nothing;
- `kpoints`: default is nothing.
"""
struct QEpw <: FileFormat end
"""
The format of wave function in `pwscf.save`.

	read(path, ::Type{QEwfc}; kwargs...) -> QEwfc

Obtain the format from the suffix. See more about [`QEwfc_dat`] and [`QEwfc_hdf5`].
"""
struct QEwfc <: FileFormat
	ik::Int #index of kpoint.
	xk::ReducedCoordinates{Float64}
	ispin::Int #1: wospin or noncolin.
	gamma_only::Bool #only gamma.
	scalef::Float64
	ngw::Int #don't know!
	igwx::Int #the number of G or components
	npol::Int #1: wospin or collin, 2: noncollin.
	nbnd::Int
	rlattice::ReciprocalLattice{Float64}
	Glist::Vector{ReducedCoordinates{Int}}
	components::Matrix{ComplexF64} #[npol * igwx, nbnd]
end
"""
The format of wave function in `pwscf.save/wfc.dat`.

	read(path/io, ::Type{QEwfc_dat}; convert = "native") -> QEwfc

- `convert`: used by [`FortranFile`](https://juliadata.org/FortranFiles.jl/stable/files/#FortranFiles.FortranFile).
"""
struct QEwfc_dat <: FileFormat end
"""
The format of wave function in `pwscf.save/wfc.hdf5`.

	read(path, ::Type{QEwfc_hdf5}) -> QEwfc

"""
struct QEwfc_hdf5 <: FileFormat end
"""
The format of `pwscf.save/data-file-schema.xml`.

	read(path, ::Type{QE_xml_new}; period = [1, 1, 1]) -> Dict{String, Any}

"""
struct QE_xml_new <: FileFormat end
"""
Read data from the `pwscf.save` directory generated by Quantum ESPRESSO (QE), and compute Wannier functions 
in the plane-wave basis using the unitary transformation matrix.

	read(savefolder, ::Type{QE_wannier}; wfcspin = nothing, period = [1, 1, 1]
		bandindex, u_matrix, u_matrix_opt = Vector{Matrix{ComplexF64}}(undef, 0)) -> WannierPWKgrid

# Arguments
- `savefolder::AbstractString`: Path to the `pwscf.save` folder generated by QE.
- `wfcspin::Union{Symbol, Nothing}`: Optional; specify `:up` or `:dw` for collinear spin-polarized calculations 
  (leave as `nothing` for non-spin-polarized systems).
- `bandindex::Vector{Vector{Int}}`: Indices of bands to be included in the Wannier function calculation.
- `u_matrix::Vector{Matrix{<:Number}}`: Core unitary transformation matrix for Wannier projection.
- `u_matrix_opt::Vector{Matrix{<:Number}}`: Optional; unitary transformation matrix for disentangling 
  (leave as an empty vector if not used).

# Core Calculation Logic
For each k-point index `ik`:
- If `u_matrix_opt` is non-empty:
```julia
wannier[ik] = (QE_wfc[:, bandindex[ik]] * u_matrix_opt[ik]) * u_matrix[ik]
```
- If u_matrix_opt is empty:
```julia
wannier[ik] = QE_wfc[:, bandindex[ik]] * u_matrix[ik]
```

shortcut method:
	read(savefolder, chkdata::wannier90_chk, ::Type{QE_wannier}; wfcspin = nothing, period = [1, 1, 1]) -> WannierPWKgrid
"""
struct QE_wannier <: FileFormat end
