struct RealCoulombGauss <: RealCoulomb
	ϵ::Float64
	α::Float64
	coff::Float64
	V₀::Float64
end
function (v::RealCoulombGauss)(r::AbstractVector{<:Real}; atol::Real = 1e-10)::Float64
	r = norm(r)
	return r ≤ atol ? v.V₀ : v.coff * erf(v.α * r) / r
end
function (v::RealCoulombGauss)(r::Real; atol::Real = 1e-10)::Float64
	signbit(r) && error("r should be positive")
	return r ≤ atol ? v.V₀ : v.coff * erf(v.α * r) / r
end
"""
	RealCoulomb(:gauss; ϵ::Real = 1, rcut::Real = 1, α::Real = 4.5 / rcut) -> RealCoulombGauss

Calculate Coulomb potential generated by a charge of Gaussian distribution in real space:

```math
V(r) = \\frac{e²}{4πϵ₀ϵ} \\frac{erf(α|r|)}{|r|}
```

unit: r(Å), V(eV), α(1/Å), ϵ(dimensionless).

rcut > 0.3时，`α = 4.5 / rcut` 可以保证 Gauss potential 在 `rcut` 外收敛至 bare Coulomb potential, 以1e-8的精度.

# Example

```julia
julia> V = RealCoulomb(:gauss; ϵ = 1.5, α = 2)
julia> r = [1.0, 0.0, 0.0] # or r = 1.0
julia> V(r)
julia> V(0.01; atol = 0.1) == V.V₀
```
"""
function RealCoulomb(::Val{:gauss}; ϵ::Real = 1, rcut::Real = 1, α::Real = 4.5 / rcut)
	@assert ϵ > 0 "ϵ should be positive"
	@assert rcut > 0 "rcut should be positive"
	@assert α > 0 "α should be positive"
	coff = CoulombScale / ϵ
	V₀ = coff * 2 * α / √π
	return RealCoulombGauss(ϵ, α, coff, V₀)
end
