abstract type RealCoulombKeldyshGauss <: RealCoulomb end
struct RealCoulombKeldyshGaussn0 <: RealCoulombKeldyshGauss
	r₀::Float64
	ϵ₁::Float64
	ϵ₂::Float64
	α::Float64
	αz::Float64
	coff::Float64
	V₀::Float64
	α²4::Float64
	αz2::Float64
end
function (v::RealCoulombKeldyshGaussn0)(r::AbstractVector{<:Real}; atol::Real = 1e-10)::Float64
	r = norm(r)
	return r ≤ atol ? v.V₀ : _RealCoulombKeldyshGaussn0(v, r)
end
function (v::RealCoulombKeldyshGaussn0)(r::Real; atol::Real = 1e-10)::Float64
	signbit(r) && error("r should be positive")
	return r ≤ atol ? v.V₀ : _RealCoulombKeldyshGaussn0(v, r)
end
function _RealCoulombKeldyshGaussn0(v, r)::Float64
	t₁ = 1 / (v.α²4 * r * r)
	t₂ = 1 / (v.αz2 * r)
	t₃ = r / v.r₀
	integrand(x) = besselj0(x) * exp(- t₁ * x * x) * erfcx(t₂ * x) / (t₃ + x)
	result, err = quadgk(integrand, 0.0, Inf; rtol = 1e-8, atol = 1e-10)
	return v.coff * result
end
#衰减至1/r，但需要放宽阈值，
struct RealCoulombKeldyshGauss0 <: RealCoulombKeldyshGauss
	ϵ₁::Float64
	ϵ₂::Float64
	α::Float64
	αz::Float64
	coff::Float64
	V₀::Float64
	α²4::Float64
	αz2::Float64
end
function (v::RealCoulombKeldyshGauss0)(r::AbstractVector{<:Real}; atol::Real = 1e-10)::Float64
	r = norm(r)
	return r ≤ atol ? v.V₀ : _RealCoulombKeldyshGauss0(v, r)
end
function (v::RealCoulombKeldyshGauss0)(r::Real; atol::Real = 1e-10)::Float64
	signbit(r) && error("r should be positive")
	return r ≤ atol ? v.V₀ : _RealCoulombKeldyshGauss0(v, r)
end
function _RealCoulombKeldyshGauss0(v, r)::Float64
	t₁ = 1 / (v.α²4 * r * r)
	t₂ = 1 / (v.αz2 * r)
	integrand(x) = besselj0(x) * exp(- t₁ * x * x) * erfcx(t₂ * x)
	result, err = quadgk(integrand, 0.0, Inf; rtol = 1e-8, atol = 1e-10)
	return v.coff * result / r
end
"""
	RealCoulomb(:keldysh_gauss; r₀::Real = 0, ϵ₁::Real = 1, ϵ₂::Real = 1, α::Real = 1, αz::Real = 1, atol::Real = 1e-10) -> RealCoulombKeldyshGauss

Calculate Coulomb potential generated by a charge of Gaussian distribution in 2D real space:

```math
V(r) = 
```

unit: r(Å), V(eV),  r₀(Å), ϵ₁(dimensionless), ϵ₂(dimensionless), α(1/Å).

# Example

```julia
julia> V = RealCoulomb(:keldysh_gauss; r₀ = 1)
julia> r = [1.0, 0.0, 0.0] # or r = 1.0
julia> V(r)
```
"""
function RealCoulomb(::Val{:keldysh_gauss}; r₀::Real = 0, ϵ₁::Real = 1, ϵ₂::Real = 1, α::Real = 1, αz::Real = 1, atol::Real = 1e-10)
	@assert r₀ ≥ 0 "r₀ should be positive"
	@assert ϵ₁ > 0 "ϵ₁ should be positive"
	@assert ϵ₂ > 0 "ϵ₂ should be positive"
	@assert α > 0 "α should be positive"
	@assert αz > 0 "αz should be positive"
	ϵd = (ϵ₁ + ϵ₂) / 2
	α²4 = 4 * α * α
	αz2 = 2 * αz
	if r₀ ≤ atol
		coff = CoulombScale / ϵd

		t₁ = 1 / α²4
		t₂ = 1 / αz2
		integrand0(q) = exp(- t₁ * q * q) * erfcx(t₂ * q)
		result, err = quadgk(integrand0, 0.0, Inf; rtol = 1e-8, atol = 1e-10)
		V₀ = coff * result

		return RealCoulombKeldyshGauss0(ϵ₁, ϵ₂, α, αz, coff, V₀, α²4, αz2)
	else
		coff = CoulombScale / (ϵd * r₀)

		t₁ = 1 / α²4
		t₂ = 1 / αz2
		t₃ = 1 / r₀
		integrand(q) = exp(- t₁ * q * q) * erfcx(t₂ * q) / (t₃ + q)
		result, err = quadgk(integrand, 0.0, Inf; rtol = 1e-8, atol = 1e-10)
		V₀ = coff * result

		return RealCoulombKeldyshGaussn0(r₀, ϵ₁, ϵ₂, α, αz, coff, V₀, α²4, αz2)
	end
end
