struct RealCoulombPoint <: RealCoulomb
	ϵ::Float64
	coff::Float64
end
function (v::RealCoulombPoint)(r::AbstractVector{<:Real}; atol::Real = 1e-10)::Float64
	r = norm(r)
	return r ≤ atol ? 0.0 : v.coff / r
end
function (v::RealCoulombPoint)(r::Real; atol::Real = 1e-10)::Float64
	signbit(r) && error("r should be positive")
	return r ≤ atol ? 0.0 : v.coff / r
end
"""
	RealCoulomb(:point; ϵ::Real = 1) -> RealCoulombPoint

Calculate Coulomb potential generated by a point charge in real space:

```math
V(r) = \\frac{e²}{4πϵ₀ϵ} \\frac{1}{|r|}
```

unit: r(Å), V(eV), ϵ(dimensionless).

# Example

```julia
julia> V = RealCoulomb(:point; ϵ = 1.5)
julia> r = [1.0, 0.0, 0.0] # or r = 1.0
julia> V(r)
julia> V(0.01; atol = 0.1) == 0
```
"""
function RealCoulomb(::Val{:point}; ϵ::Real = 1.0)
	@assert ϵ > 0 "ϵ should be positive"
	coff = CoulombScale / ϵ
	return RealCoulombPoint(ϵ, coff)
end
