struct RealKeldyshGauss2D <: RealCoulomb
	r₀::Float64
	ϵ₁::Float64
	ϵ₂::Float64
	α::Float64
	CoulombScaleϵ::Float64
	V₀::Float64
	α²4::Float64
end
function (v::RealKeldyshGauss2D)(r::AbstractVector{<:Real}; atol::Real = 1e-10)::Float64
	r = norm(r)
	return r ≤ atol ? v.V₀ : _RealKeldyshGauss2D(v, r)
end
function (v::RealKeldyshGauss2D)(r::Real; atol::Real = 1e-10)::Float64
	signbit(r) && error("r should be positive")
	return r ≤ atol ? v.V₀ : _RealKeldyshGauss2D(v, r)
end
function _RealKeldyshGauss2D(v, r)::Float64
	t₁ = 1 / (v.α²4 * r * r)
	t₂ = r / v.r₀
	integrand(x) = besselj0(x) * exp(-x * x * t₁) / (t₂ + x)
	result, err = quadgk(integrand, 0.0, Inf; rtol = 1e-8, atol = 1e-10)
	return v.CoulombScaleϵ * result
end
#衰减至1/r，但需要放宽阈值，
struct RealKeldyshGauss2D0 <: RealCoulomb
	ϵ₁::Float64
	ϵ₂::Float64
	α::Float64
	CoulombScaleϵ::Float64
	V₀::Float64
	α²4::Float64
end
function (v::RealKeldyshGauss2D0)(r::AbstractVector{<:Real}; atol::Real = 1e-10)::Float64
	r = norm(r)
	return r ≤ atol ? v.V₀ : _RealKeldyshGauss2D0(v, r)
end
function (v::RealKeldyshGauss2D0)(r::Real; atol::Real = 1e-10)::Float64
	signbit(r) && error("r should be positive")
	return r ≤ atol ? v.V₀ : _RealKeldyshGauss2D0(v, r)
end
function _RealKeldyshGauss2D0(v, r)::Float64
	t = v.α * v.α * r * r / 2
	return v.CoulombScaleϵ * √π * v.α * SpecialFunctions._besseli(Float64(0), ComplexF64(t), Int32(2))
	# v.CoulombScaleϵ * √π * v.α * besseli(0, t) * exp(-t)
end
"""
	RealKeldyshGauss(; r₀::Real = 1, ϵ₁::Real = 1, ϵ₂::Real = 1, α::Real = 1) -> RealKeldyshGauss

Calculate Coulomb potential generated by a charge of Gaussian distribution in 2D real space:

```math
V(r) = 
```

unit: r(Å), V(eV),  r₀(Å), ϵ₁(dimensionless), ϵ₂(dimensionless), α(1/Å).

# Example

```julia
julia> V = RealKeldyshGauss(; r₀ = 1)
julia> r = [1.0, 0.0, 0.0] # or r = 1.0
julia> V(r)
```
"""
function RealKeldyshGauss2D(; r₀::Real = 0, ϵ₁::Real = 1, ϵ₂::Real = 1, rcut::Real = 1, α::Real = 4.5 / rcut, atol::Real = 1e-10)
	@assert r₀ ≥ 0 "r₀ should be positive"
	@assert ϵ₁ > 0 "ϵ₁ should be positive"
	@assert ϵ₂ > 0 "ϵ₂ should be positive"
	@assert α > 0 "α should be positive"
	ϵd = (ϵ₁ + ϵ₂) / 2

	if r₀ ≤ atol
		CoulombScaleϵ = CoulombScale / ϵd
		α²4 = 4 * α * α

		V₀ = CoulombScaleϵ * α * √π

		return RealKeldyshGauss2D0(ϵ₁, ϵ₂, α, CoulombScaleϵ, V₀, α²4)
	else
		CoulombScaleϵ = CoulombScale / (ϵd * r₀)
		α²4 = 4 * α * α

		t = 1 / (2 * α * r₀)
		integrand(x) = exp(-x * x) / (t + x)
		result, err = quadgk(integrand, 0.0, Inf; rtol = 1e-8, atol = 1e-10)
		V₀ = CoulombScaleϵ * result

		return RealKeldyshGauss2D(r₀, ϵ₁, ϵ₂, α, CoulombScaleϵ, V₀, α²4)
	end
end
