struct PeriodCoulombGauss <: PeriodCoulomb
	lattice::Lattice{Float64}
	kgrid::Vec3{Int}
	ϵ::Float64
	α::Float64
	δ::Float64
	φ::ReciprocalCoulombGauss
	nkG::Int
	allkG::Vector{ReducedCoordinates{Rational{Int}}}
	φkG::Vector{Float64}
	head::Float64
end
(v::PeriodCoulombGauss)(r::AbstractVector{<:Real}) = v(ReducedCoordinates(r))
function (v::PeriodCoulombGauss)(r::ReducedCoordinates)::Float64
	return sum(ikG -> v.φkG[ikG] * cospi(2 * (v.allkG[ikG] ⋅ r)), Base.OneTo(v.nkG)) + v.head
end
"""
	PeriodCoulomb(:gauss, lattice, kgrid; ϵ::Real = 1, rcut::Real = 1, α::Real = 4.5 / rcut, δ::Real = 1e-8, head = nothing) -> PeriodCoulombGauss

Calculate Coulomb potential generated by a charge of Gaussian distribution in real space in a periodic system:

```math
V(R+r) = \\frac{1}{nk} \\sum_{kG} \\phi(k+G) e^{i (k+G) \\cdot (R + r)}
```

# Example

```julia
julia> V
julia> r = [1.0, 0.0, 0.0]
julia> V(r)
```
"""
function PeriodCoulomb(::Val{:gauss}, lattice::Union{AbstractMatrix{<:Real}, Lattice},
	kgrid::Union{MonkhorstPack, RedKgrid, AbstractVector{<:Integer}, NTuple{3, <:Integer}};
	ϵ::Real = 1, rcut::Real = 1, α::Real = 4.5 / rcut, δ::Real = 1e-8,
	head::Union{Number, Nothing} = nothing,
)
	@assert rcut > 0 "rcut should be positive"

	lattice = Lattice(parent(lattice))
	Ω = abs(det(parent(lattice)))
	φ = ReciprocalGauss(; ϵ, α, Ω)

	if kgrid isa AbstractVector || kgrid isa NTuple
		@assert all(>(0), kgrid) "kgrid should be positive"
		kgrid = RedKgrid(MonkhorstPack(kgrid[1], kgrid[2], kgrid[3]))
	else
		kgrid = RedKgrid(MonkhorstPack(kgrid.kgrid_size))
	end

	nk = length(kgrid)
	rlattice = reciprocal(lattice)

	allkG, allkG_norm2 = _PeriodCoulombGauss_kG(rlattice, kgrid, α, δ)

	invnk_time_2 = 2 / nk
	φkG = map(kG2 -> φ(Val(:k²), kG2; atol = 0.0) * invnk_time_2, allkG_norm2)
	if isnothing(head)
		head = φ(Val(:head), rlattice, kgrid.kgrid_size) / nk
	end

	return PeriodCoulombGauss(lattice, kgrid.kgrid_size, ϵ, α, δ,
		φ, length(allkG), allkG, φkG, head)
end
function _PeriodCoulombGauss_kG(rlattice, kgrid, α, δ)
	rldot = parent(rlattice)
	rldot = Mat3(transpose(rldot) * rldot)

	dk = 1 .// kgrid.kgrid_size
	dk_atol = minimum(dk) // 2

	kG2_max = -4 * α * α * log(δ)
	Gnorm_max = sqrt(kG2_max) + norm(parent(rlattice))
	Ggrid = gridindex(rlattice, Gnorm_max, Val(3))
	allkG = reshape([k + G for k in kgrid, G in Ggrid], :)
	filter!(kG->_ispositive_vector(kG; atol = dk_atol), allkG)
	allkG_norm2 = map(kG -> kG ⋅ (rldot * kG), allkG)
	I = allkG_norm2 .≤ kG2_max
	allkG = allkG[I]
	allkG_norm2 = allkG_norm2[I]

	return allkG, allkG_norm2
end
