struct PeriodCoulombKeldyshGauss <: PeriodCoulomb
	lattice::Lattice{Float64}
	kgrid::Vec3{Int}
	period::Vec3{Bool}
	xyindex::SVector{2, Int}
	zindex::Int
	lattice2D::SMatrix{2, 2, Float64, 4}
	kgrid2D::SVector{2, Int}
	r₀::Float64
	ϵ₁::Float64
	ϵ₂::Float64
	α::Float64
	αz::Float64
	δ::Float64
	φ::ReciprocalCoulombKeldyshGauss
	nkG::Int
	allkG::Vector{SVector{2, Rational{Int}}}
	φkG::Vector{Float64}
	head::Float64
end
# xyindex should correspond to allkG.
function (v::PeriodCoulombKeldyshGauss)(r::AbstractVector{<:Real})
	if length(r) == 2
		return v(SVector{2}(r))
	else
		return v(SVector{2}(r[v.xyindex]))
	end
end
(v::PeriodCoulombKeldyshGauss)(r::ReducedCoordinates) = v(SVector{2}(r[v.xyindex]))
function (v::PeriodCoulombKeldyshGauss)(r::SVector{2, <:Real})::Float64
	return sum(ikG -> v.φkG[ikG] * cospi(2 * (v.allkG[ikG] ⋅ r)), Base.OneTo(v.nkG)) + v.head
end
"""
	PeriodCoulomb(:keldysh_gauss, lattice, kgrid; ϵ::Real = 1, rcut::Real = 1, α::Real = 4.5 / rcut, δ::Real = 1e-8, head = nothing) -> PeriodCoulombKeldyshGauss

Calculate Coulomb potential generated by a charge of Gaussian distribution in real space in a periodic system:

```math
V(R+r) = \\frac{1}{nk} \\sum_{kG} \\phi(k+G) e^{i (k+G) \\cdot (R + r)}
```

# Example

```julia
julia> V
julia> r = [1.0, 0.0, 0.0]
julia> V(r)
```
"""
function PeriodCoulomb(::Val{:keldysh_gauss}, lattice::Union{AbstractMatrix{<:Real}, Lattice},
	kgrid::Union{MonkhorstPack, RedKgrid, AbstractVector{<:Integer}, NTuple{3, <:Integer}};
	period = Bool[1, 1, 0],
	r₀::Real = 0, ϵ₁::Real = 1, ϵ₂::Real = 1, α::Real = 1.0, αz::Real = 1.0, atol::Real = 0,
	δ::Real = 1e-8, head::Union{Number, Nothing} = nothing,
)
	lattice = Lattice(parent(lattice))
	rlattice = reciprocal(lattice)

	period = Vec3{Bool}(period)
	@assert count(period) == 2 "Exactly two dimensions should be periodic."
	if !period[1]
		xyindex = SVector{2, Int}(2, 3)
		zindex = 1
	elseif !period[2]
		xyindex = SVector{2, Int}(3, 1)
		zindex = 2
	else
		xyindex = SVector{2, Int}(1, 2)
		zindex = 3
	end

	@assert all(iszero, lattice[xyindex, zindex]) "Wrong lattice: the non-periodic direction should be perpendicular to the periodic plane."
	@assert all(iszero, lattice[zindex, xyindex]) "Wrong lattice: the non-periodic direction should be perpendicular to the periodic plane."

	lattice2D = SMatrix{2, 2, Float64, 4}(lattice[xyindex, xyindex])
	𝐚 = lattice2D[:, 1]
	𝐛 = lattice2D[:, 2]
	S = abs(𝐚[1] * 𝐛[2] - 𝐚[2] * 𝐛[1])
	φ = ReciprocalKeldyshGauss(; r₀, ϵ₁, ϵ₂, α, αz, S, atol)

	if kgrid isa AbstractVector || kgrid isa NTuple
		@assert all(>(0), kgrid) "kgrid should be positive"
		kgridsize = [kgrid[1], kgrid[2], kgrid[3]]
	else
		kgridsize = kgrid.kgrid_size
	end
	@assert kgridsize[zindex] == 1 "The kgrid should be 2D for PeriodCoulombKeldyshGauss."
	kgrid = RedKgrid(MonkhorstPack(kgridsize))
	nk = length(kgrid)

	allkG, allkG_norm2 = _PeriodCoulombKeldyshGauss_kG(rlattice, kgrid, xyindex, α, δ)

	rlattice2D = SMatrix{2, 2, Float64, 4}(rlattice[xyindex, xyindex])
	kgridsize2D = SVector{2, Int}(kgridsize[xyindex])

	invnk_time_2 = 2 / nk
	φkG = map(kG2 -> φ(Val(:k²), kG2; atol = 0.0) * invnk_time_2, allkG_norm2)
	if isnothing(head)
		head = φ(Val(:head), rlattice2D, kgridsize2D) / nk
	end

	return PeriodCoulombKeldyshGauss(
		lattice, kgridsize, period, xyindex, zindex, lattice2D, kgridsize2D,
		r₀, ϵ₁, ϵ₂, α, αz, δ, φ,
		length(allkG), allkG, φkG, head)
end
function _PeriodCoulombKeldyshGauss_kG(rlattice, kgrid, xyindex, α, δ)

	dk = 1 .// kgrid.kgrid_size
	dk_atol = minimum(dk) // 2

	kG2_max = -4 * α^2 * log(δ)
	Gnorm_max = sqrt(kG2_max) + norm(parent(rlattice))
	Ggrid = gridindex(rlattice, Gnorm_max, xyindex, Val(2))
	allkG = reshape([k + G for k in kgrid, G in Ggrid], :)
	filter!(kG->_ispositive_vector(kG; atol = dk_atol), allkG)

	rldot = rlattice[xyindex, xyindex]
	rldot = SMatrix{2, 2, Float64, 4}(transpose(rldot) * rldot)
	allkG = map(kG -> SVector{2, Rational{Int}}(kG[xyindex]), allkG)

	allkG_norm2 = map(kG -> kG ⋅ (rldot * kG), allkG)
	I = allkG_norm2 .≤ kG2_max
	allkG = allkG[I]
	allkG_norm2 = allkG_norm2[I]

	return allkG, allkG_norm2
end




