struct ReciprocalCoulombGauss <: ReciprocalCoulomb
	ϵ::Float64
	α::Float64
	Ω::Float64
	coff::Float64
	α²4::Float64
end
function (v::ReciprocalCoulombGauss)(k::AbstractVector{<:Real}; atol::Real = 1e-10)::Float64
	k² = k ⋅ k
	return sqrt(k²) ≤ atol ? 0.0 : v.coff * exp(-k² / v.α²4) / k²
end
function (v::ReciprocalCoulombGauss)(k::Real; atol::Real = 1e-10)::Float64
	signbit(k) && error("k should be positive")
	return k ≤ atol ? 0.0 : begin
		k² = k * k
		v.coff * exp(-k² / v.α²4) / k²
	end
end
function (v::ReciprocalCoulombGauss)(::Val{:k²}, k²; atol::Real = 1e-10)::Float64
	signbit(k²) && error("k² should be positive")
	return k² ≤ atol ? 0.0 : v.coff * exp(-k² / v.α²4) / k²
end
function (v::ReciprocalCoulombGauss)(::Val{:k²scale}, k::AbstractVector{<:Real})::Float64
	k² = k ⋅ k
	return v.coff * exp(-k² / v.α²4)
end
function (v::ReciprocalCoulombGauss)(::Val{:k²scale}, k::Real)::Float64
	signbit(k) && error("k should be positive")
	k² = k * k
	return v.coff * exp(-k² / v.α²4)
end
function (v::ReciprocalCoulombGauss)(::Val{:head}, nk::Integer)::Float64
	signbit(nk) && error("nk should be positive")
	NΩ = nk * v.Ω
	qsz = (6 * π^2 / NΩ)^(1 // 3)
	return v.coff * NΩ * v.α * erf(qsz / (2 * v.α)) / (2 * π^(3 // 2))
end
function (v::ReciprocalCoulombGauss)(::Val{:head}, rlattice::Union{ReciprocalLattice, AbstractMatrix{<:Real}}, kgrid::Union{AbstractVector, Tuple})::Float64
	all(signbit, kgrid) && error("nk should be positive")

	minirlattice = ReciprocalLattice(rlattice[1:3, 1] ./ kgrid[1], rlattice[1:3, 2] ./ kgrid[2], rlattice[1:3, 3] ./ kgrid[3])
	miniFBZ = WignerSeitz(minirlattice)

	qsz2 = minimum(miniFBZ.offsets) / 2
	qsz = sqrt(qsz2)

	a = Vector{Float64}(undef, 3)
	b = Vector{Float64}(undef, 3)
	for i in 1:3
		(a[i], b[i]) = extrema(k -> k[i], miniFBZ.normals)
	end

	function integrand(k)
		k² = k[1] * k[1] + k[2] * k[2] + k[3] * k[3]
		k² < qsz2 && return 0.0
		k ∈ miniFBZ && return exp(-k² / v.α²4) / k²
		return 0.0
	end

	(result, err) = hcubature(integrand, a, b; norm = abs, rtol = 1e-8, atol = 1e-10)
	result_sphere = 4 * π^(3 // 2) * v.α * erf(qsz / (2 * v.α))

	nk = prod(kgrid)
	NΩ = nk * v.Ω
	return v.coff * (result + result_sphere) * NΩ / (2π)^3
end
"""
	ReciprocalCoulomb(:gauss; ϵ::Real = 1, α::Real = 1, Ω::Real = 1) -> ReciprocalCoulombGauss

Under 3D cases, calculate Coulomb potential generated by a charge of Gaussian distribution in reciprocal space:

```math
V(k) = \\frac{e²}{Ωϵ₀ϵ} \\frac{1}{k²} e^{-\\frac{k²}{4α²}}
```

unit: k(1/Å), V(eV), Ω(Å³), α(1/Å), ϵ(dimensionless).

# Example

```julia
julia> V = ReciprocalCoulomb(:gauss; ϵ = 1.5, α = 1.0, Ω = 10.0)
julia> k = [1.0, 0.0, 0.0] # or k = 1.0
julia> V(k)
```

We provide a method to calculate the head value:

```math
V(head) = \\frac{NΩ}{(2π)³} \\int_{0}^{q_{sz}} V(k) 4πk² dk , 
\\frac{4π}{3}q_{sz}^3 = \\frac{(2π)³}{NΩ}
```

```julia
julia> V(:head, N)
```
"""
function ReciprocalCoulomb(::Val{:gauss}; ϵ::Real = 1, rcut::Real = 1, α::Real = 4.5 / rcut, Ω::Real = 1)
	@assert ϵ > 0 "ϵ should be positive"
	@assert rcut > 0 "rcut should be positive"
	@assert α > 0 "α should be positive"
	@assert Ω > 0 "Ω should be positive"
	coff = CoulombScale * 4π / (Ω * ϵ)
	α²4 = 4 * α^2
	return ReciprocalCoulombGauss(ϵ, α, Ω, coff, α²4)
end
# anisotropic
# 目前而言，各向同性的高斯势精度已基本满足，且存在实空间简单的表达式。
# 各向异性的实空间Gauss势可以通过一个椭圆积分表示。
struct ReciprocalCoulombGaussAnisotropic <: ReciprocalCoulomb
	ϵ::Float64
	α::Vec3{Float64}
	Ω::Float64
	coff::Float64
	α²4::Vec3{Float64}
end
function (v::ReciprocalCoulombGaussAnisotropic)(k::AbstractVector{<:Real}; atol::Real = 1e-10)::Float64
	kx², ky², kz² = k[1] * k[1], k[2] * k[2], k[3] * k[3]
	k² = kx² + ky² + kz²
	k = sqrt(k²)
	return k ≤ atol ? 0.0 : v.coff * exp(-(kx² / v.α²4[1] + ky² / v.α²4[2] + kz² / v.α²4[3])) / k²
end
function (v::ReciprocalCoulombGaussAnisotropic)(::Val{:k²scale}, k::AbstractVector{<:Real})::Float64
	kx², ky², kz² = k[1] * k[1], k[2] * k[2], k[3] * k[3]
	return v.coff * exp(-(kx² / v.α²4[1] + ky² / v.α²4[2] + kz² / v.α²4[3]))
end
function (v::ReciprocalCoulombGaussAnisotropic)(::Val{:head}, nk::Integer)::Float64
	#实际计算较为麻烦，使用hcubature，但是需要将原函数分离为平滑部分和发散部分1/k^2，平滑部分直接数值积分，发散部分进行解析求解，注意平滑部分在原点附近的极限行为需要避免浮点数极限。
	error("To be continued!")
end
function (v::ReciprocalCoulombGaussAnisotropic)(::Val{:head}, rlattice::Union{ReciprocalLattice, AbstractMatrix{<:Real}}, kgrid::Union{AbstractVector, Tuple})::Float64
	error("To be continued!")
end
function ReciprocalCoulomb(::Val{:gaussanisotropic}; ϵ::Real = 1, α::AbstractVector{<:Real} = [1, 1, 1], Ω::Real = 1)
	@assert ϵ > 0 "ϵ should be positive"
	@assert rcut > 0 "rcut should be positive"
	@assert α > 0 "α should be positive"
	@assert Ω > 0 "Ω should be positive"
	coff = CoulombScale * 4π / (Ω * ϵ)
	α = Vec3(α)
	α²4 = 4 .* α .* α
	return ReciprocalCoulombGaussAnisotropic(ϵ, α, Ω, coff, α²4)
end
