struct ReciprocalCoulombPoint <: ReciprocalCoulomb
	ϵ::Float64
	Ω::Float64
	coff::Float64
end
function (v::ReciprocalCoulombPoint)(k::AbstractVector{<:Real}; atol::Real = 1e-10)::Float64
	k² = k ⋅ k
	return √k² ≤ atol ? 0.0 : v.coff / k²
end
function (v::ReciprocalCoulombPoint)(k::Real; atol::Real = 1e-10)::Float64
	signbit(k) && error("k should be positive")
	return k ≤ atol ? 0.0 : v.coff / (k * k)
end
function (v::ReciprocalCoulombPoint)(::Val{:k²}, k²; atol::Real = 1e-10)::Float64
	signbit(k²) && error("k² should be positive")
	return k² ≤ atol ? 0.0 : v.coff / k²
end
function (v::ReciprocalCoulombPoint)(::Val{:k²scale}, k::AbstractVector{<:Real})::Float64
	return v.coff
end
function (v::ReciprocalCoulombPoint)(::Val{:k²scale}, k::Real)::Float64
	signbit(k) && error("k should be positive")
	return v.coff
end
function (v::ReciprocalCoulombPoint)(::Val{:head}, nk::Integer)::Float64
	signbit(nk) && error("nk should be positive")
	NΩ = nk * v.Ω
	qsz = (6 * π^2 / NΩ)^(1 // 3)
	return v.coff * NΩ * qsz / (2 * π^2)
end
function (v::ReciprocalCoulombPoint)(::Val{:head}, rlattice::Union{ReciprocalLattice, AbstractMatrix{<:Real}}, kgrid::Union{AbstractVector, Tuple})::Float64
	all(signbit, kgrid) && error("nk should be positive")

	minirlattice = ReciprocalLattice(rlattice[1:3, 1] ./ kgrid[1], rlattice[1:3, 2] ./ kgrid[2], rlattice[1:3, 3] ./ kgrid[3])
	miniFBZ = WignerSeitz(minirlattice)

	qsz2 = minimum(miniFBZ.offsets) / 2
	qsz = sqrt(qsz2)

	a = Vector{Float64}(undef, 3)
	b = Vector{Float64}(undef, 3)
	for i in 1:3
		(a[i], b[i]) = extrema(k -> k[i], miniFBZ.normals)
	end

	function integrand(k)
		k² = k[1] * k[1] + k[2] * k[2] + k[3] * k[3]
		k² < qsz2 && return 0.0
		k ∈ miniFBZ && return 1 / k²
		return 0.0
	end

	(result, err) = hcubature(integrand, a, b; norm = abs, rtol = 1e-8, atol = 1e-10)
	result_sphere = 4π * qsz

	nk = prod(kgrid)
	NΩ = nk * v.Ω
	return v.coff * (result + result_sphere) * NΩ / (2π)^3
end
"""
	ReciprocalCoulomb(:point; ϵ::Real = 1, Ω::Real = 1) -> ReciprocalCoulombPoint

Calculate Coulomb potential generated by a point charge in reciprocal space:

```math
V(k) = \\frac{e²}{Ωϵ₀ϵ} \\frac{1}{k²}
```

unit: k(1/Å), V(eV), Ω(Å³), ϵ(dimensionless).

# Example

```julia
julia> V = ReciprocalCoulomb(:point; ϵ = 1.5, Ω = 10.0)
julia> k = [1.0, 0.0, 0.0] # or k = 1.0
julia> V(k)
```

We provide a method to calculate the head value:

```math
V(head) = \\frac{NΩ}{(2π)³} \\int_{0}^{q_{sz}} V(k) 4πk² dk , 
\\frac{4π}{3}q_{sz}^3 = \\frac{(2π)³}{NΩ}
```

```julia
julia> V(:head, N)
```
"""
function ReciprocalCoulomb(::Val{:point}; ϵ::Real = 1, Ω::Real = 1)
	@assert ϵ > 0 "ϵ should be positive"
	@assert Ω > 0 "Ω should be positive"
	coff = CoulombScale * 4π / (Ω * ϵ)
	return ReciprocalCoulombPoint(ϵ, Ω, coff)
end
