struct ReciprocalGauss2D <: ReciprocalCoulomb
	ϵ::Float64
	α::Float64
	S::Float64
	CoulombScaleϵ::Float64
	α2::Float64
end
function (v::ReciprocalGauss2D)(k::AbstractVector{<:Real}, z::Real; atol::Real = 1e-10)::Float64
	k = sqrt(k ⋅ k)
	return k ≤ atol ? 0.0 : begin
		z = abs(z)
		αz = v.α * z
		ekz = exp(k * z)
		k2α = k / (v.α2)
		v.CoulombScaleϵ * (erfc(k2α + αz) * ekz + erfc(k2α - αz) / ekz) / k
	end
end
function (v::ReciprocalGauss2D)(k::Real, z::Real; atol::Real = 1e-10)::Float64
	signbit(k) && error("k should be positive")
	return k ≤ atol ? 0.0 : begin
		z = abs(z)
		αz = v.α * z
		ekz = exp(k * z)
		k2α = k / (v.α2)
		v.CoulombScaleϵ * (erfc(k2α + αz) * ekz + erfc(k2α - αz) / ekz) / k
	end
end
function (v::ReciprocalGauss2D)(::Val{:head}, nk::Integer, z::Real; atol::Real = 1e-10)::Float64
	signbit(nk) && error("nk should be positive")
	NS = nk * v.S
	qsz = √(4 * π / NS)

	z = abs(z)

	qsz2α = qsz / (v.α2)
	if z ≤ atol
		α2sπ = v.α2 / √π
		return v.CoulombScaleϵ * NS * (qsz * erfc(qsz2α) - α2sπ * exp(-qsz2α^2) + α2sπ) / π
	else
		eqz = exp(qsz * z)
		αz = v.α * z
		return v.CoulombScaleϵ * NS * (erfc(qsz2α + αz) * eqz - erfc(qsz2α - αz) / eqz + 2 * erf(αz)) / (2π * z)
	end
end
"""
	ReciprocalGauss2D(; ϵ::Real = 1, α::Real = 1, S::Real = 1) -> ReciprocalGauss2D

Under 2D cases, calculate Coulomb potential generated by a charge of Gaussian distribution in reciprocal space:

```math
V(k, z) = \\frac{e²}{4Sϵ₀ϵ} \\frac{1}{k} \\left[ e^{kz} erfc(\\frac{k}{2α} + αz) + e^{-kz} erfc(\\frac{k}{2α} - αz) \\right]
```

unit: k(1/Å), z(Å), V(eV), S(Å²), α(1/Å), ϵ(dimensionless).

# Example

```julia
julia> V = ReciprocalGauss2D(; ϵ = 1.5, α = 1.0, S = 10.0)
julia> k = [1.0, 0.0, 0.0] # or k = 1.0
julia> z = 0.5
julia> V(k, z)
```

We provide a method to calculate the head value:

```math
V(head, z) = \\frac{NS}{(2π)²} \\int_{0}^{q_{sz}} V(k, z) 2πk dk , 
πq_{sz}^2 = \\frac{(2π)²}{NS}
```

```julia
julia> V(:head, N, z)
```
"""
function ReciprocalGauss2D(; ϵ::Real = 1.0, α::Real = 1.0, S::Real = 1.0)
	@assert ϵ > 0 "ϵ should be positive"
	@assert α > 0 "α should be positive"
	@assert S > 0 "S should be positive"
	CoulombScaleϵ = CoulombScale * π / (S * ϵ)
	α2 = 2 * α
	return ReciprocalGauss2D(ϵ, α, S, CoulombScaleϵ, α2)
end
