export ReciprocalCoulomb
"""
	abstract type ReciprocalCoulomb <: AbstractCoulomb end

The Coulomb potential defined in reciprocal space.
"""
abstract type ReciprocalCoulomb <: AbstractCoulomb end

ReciprocalCoulomb(sym::Symbol, args...; kwargs...) = ReciprocalCoulomb(Val(sym), args...; kwargs...)
(v::ReciprocalCoulomb)(sym::Symbol, args...; kwargs...) = v(Val(sym), args...; kwargs...)

include("./Point.jl")
include("./Gauss.jl")
include("./Keldysh.jl")
include("./KeldyshGauss.jl")




# TODO
struct ReciprocalTruncatedInverseR2D <: ReciprocalCoulomb
	ϵ::Float64
	Ω::Float64
	CoulombScaleϵ::Float64
	R::Float64
end
function (v::ReciprocalTruncatedInverseR2D)(k::AbstractVector{<:Real})::Float64
end
function (v::ReciprocalTruncatedInverseR2D)(k::Real)::Float64
end
function (v::ReciprocalTruncatedInverseR2D)(::Val{:head}, nk::Integer)::Float64
end
"""
	ReciprocalTruncatedInverseR2D(; ϵ::Real = 1, Ω::Real = 1) -> ReciprocalTruncatedInverseR2D

Calculate Coulomb potential generated by a point charge in reciprocal space:

```math
V(k) = \\frac{e²}{Ωϵ₀ϵ} \\frac{1}{k²} \\left[1 + e^{-k_{xy}R} \\frac{k_z}{k_{xy}}sin(k_zR) - e^{-k_{xy}R}cos(k_zR)\\right]
```

unit: k(1/Å), V(eV), Ω(Å³), ϵ(dimensionless), R(Å).

# Example

```julia
julia> V = ReciprocalTruncatedInverseR2D(; ϵ = 1.5, Ω = 10.0, R = 1.0)
julia> k = [1.0, 0.0, 0.0]
julia> V(k)
```

We provide a method to calculate the head value: unuse

```math
V(head) = \\frac{NΩ}{(2π)³} \\int_{0}^{q_{sz}} V(k) 4πk² dk , 
\\frac{4π}{3}q_{sz}^3 = \\frac{(2π)³}{NΩ}
```

```julia
julia> V(:head, N)
```
"""
function ReciprocalTruncatedInverseR2D(; ϵ::Real = 1, Ω::Real = 1, R::Real = 1)
	error("To be continued")
	@assert ϵ > 0 "ϵ should be positive"
	@assert Ω > 0 "Ω should be positive"
	@assert R > 0 "R should be positive"
	CoulombScaleϵ = CoulombScale * 4π / (Ω * ϵ)
	return ReciprocalTruncatedInverseR2D(ϵ, Ω, CoulombScaleϵ, R)
end






# struct ReciprocalGaussAnisotropy3D <: ReciprocalCoulomb
# 	ϵ::Mat3{Float64}
# 	α::Float64
# 	Ω::Float64
# 	CoulombScale::Float64
# 	α²4::Float64
# end
# function (v::ReciprocalGaussAnisotropy3D)(k::AbstractVector{<:Real})::Float64
# 	k2 = k[1] * k[1] + k[2] * k[2] + k[3] * k[3]
# 	return k2 == 0 ? 0.0 : v.CoulombScale * exp(-k2 / v.α²4) / (transpose(k) * v.ϵ * k)
# end
# function ReciprocalGaussAnisotropy3D(; ϵ::AbstractMatrix{<:Real} = [1 0 0; 0 1 0; 0 0 1], α::Real = 1, Ω::Real = 1)
# 	CoulombScale = CoulombScale * 4π / Ω
# 	α²4 = 4 * α^2
# 	return ReciprocalGaussAnisotropy3D(ϵ, α, Ω, CoulombScale, α²4)
# end
