function Base.write(io::IO, wannier::Array{WT, 3}, ::Type{wannier90_xsf}; comment = "",
	cell::Cell, wannier_range::NTuple{3, <:Integer}, origin::Union{AbstractVector{<:Real}, Nothing} = nothing) where {WT <: Number}

	if WT <: Complex
		max_imag_real_ratio = maximum(wannier) do v
			abs2(v) < 1e-4 ? 0 : abs(imag(v) / real(v))
		end
		comment = comment * " ; Maximum Im/Re Ratio = $max_imag_real_ratio"
		wannier = real(wannier)
	end

	if cell isa Cell{<:CartesianCoordinates}
		cell = convert(cell)
	end
	lattice = parent(cell.lattice)

	if isnothing(origin)
		origin = -lattice * [floor.(Int, (wannier_range .- 1) ./ 2)...]
		origin = Vec3(origin)
	end

	grid_size = size(wannier)

	grid_vecs = Matrix{Float64}(undef, 3, 3)
	for i in 1:3
		grid_vecs[:, i] = lattice[:, i] * wannier_range[i] * (grid_size[i] - 1) / grid_size[i]
	end

	wannier = wannier90_xsf(cell, origin, grid_vecs, grid_size, wannier)

	write(io, wannier; comment)

	return nothing
end
function Base.write(io::IO, wannier::wannier90_xsf; comment = "")

	println(io, "# ", comment)
	println(io, "# Generated by the Julia code")
	println(io, "# ", Dates.format(Dates.now(), "yyyy/m/d H:M:S"))
	println(io, "#")

	cell = wannier.cell
	println(io, "CRYSTAL")
	println(io, "PRIMVEC")
	for i in 1:3
		@printf(io, "%12.7f %12.7f %12.7f\n", cell.lattice[:, i]...)
	end
	println(io, "CONVVEC")
	for i in 1:3
		@printf(io, "%12.7f %12.7f %12.7f\n", cell.lattice[:, i]...)
	end
	println(io, "PRIMCOORD")
	@printf(io, " %6u  1\n", length(cell.location))
	if cell isa Cell{<:ReducedCoordinates}
		cell = convert(cell)
	end
	for i in eachindex(cell.location)
		@printf(io, "%-5s %12.7f %12.7f %12.7f\n", cell.name[i], cell.location[i]...)
	end

	println(io, "\n\nBEGIN_BLOCK_DATAGRID_3D")
	println(io, "3D_field")
	println(io, "BEGIN_DATAGRID_3D_UNKNOWN")

	@printf(io, " %6u %6u %6u\n", wannier.grid_size...)
	@printf(io, "%12.7f %12.7f %12.7f\n", wannier.origin...)
	for i in 1:3
		@printf(io, "%12.7f %12.7f %12.7f\n", wannier.grid_vecs[:, i]...)
	end

	ngrid = length(wannier.value)
	nline = floor(Int, ngrid // 6)
	nleft = ngrid - nline * 6
	for i in 1:nline
		@printf(io, "% 13.5E %13.5E %13.5E %13.5E %13.5E %13.5E\n", wannier.value[6*(i-1)+1:6*i]...)
	end
	if nleft ≠ 0
		for i in 1:nleft
			@printf(io, "% 13.5E", wannier.value[6*nline+i])
		end
		println(io, "")
	end
	println(io, "END_DATAGRID_3D")
	println(io, "END_BLOCK_DATAGRID_3D")

	return nothing
end
